version: 2
project_name: gituser
before:
  hooks:
    - go mod tidy
builds:
  - binary: gituser
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - "-X 'cmd.AppVersion={{.Version}}'"
release:
  prerelease: auto
universal_binaries:
  - replace: true
archives:
  - files:
      - LICENSE
      - README.md
snapshot:
  version_template: "{{ incpatch .Version }}-snapshot"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
checksum:
  name_template: "checksums.txt"
