name: release

on:
  # push:
  #   tags:
  #     - "v[0-9]+.[0-9]+.[0-9]+" # e.g., v1.0.0
  #     - "v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+" # e.g., v1.0.0-beta.1
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.24.3

      - name: Validate GoReleaser config
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: check

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BREW_TOKEN: ${{ secrets.BREW_TOKEN }}
